# Generated by Django 4.0.4 on 2022-08-29 17:30

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
                ('is_moderated', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=post.models.Comment.file_path)),
                ('is_updated', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d/%H/%M%S')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('is_updated', models.BooleanField(default=False)),
                ('is_moderated', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Change time')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='#tag')),
                ('slug', models.SlugField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'Tags_post',
            },
        ),
    ]
