# Generated by Django 4.0.4 on 2022-09-06 19:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='jpeg', keep_meta=True, null=True, quality=75, scale=1.0, size=[500, 500], upload_to='post/%Y/%m/%d/'),
        ),
    ]
