# Generated by Django 4.0.4 on 2022-08-29 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='work_tag', to='home.tags'),
        ),
        migrations.AddField(
            model_name='images',
            name='new_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.work', verbose_name='work_image'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackcontact',
            unique_together={('full_name', 'email', 'active')},
        ),
    ]
