# Generated by Django 4.0.4 on 2022-09-06 13:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=True, quality=-1, scale=None, size=[1145, 800], upload_to='works/%Y/%m/%d/%H/%M%S'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='works/%Y/%m/%d/%H/%M%S'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='works/%Y/%m/%d/%H/%M%S'),
        ),
    ]
