# Generated by Django 4.0.4 on 2022-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_social_work_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='work_tag', to='home.tags'),
        ),
    ]
