# Generated by Django 4.0.4 on 2022-09-06 19:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_images_image_alter_work_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='jpeg', keep_meta=True, quality=75, scale=1.0, size=[1920, 1350], upload_to='works/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='jpeg', keep_meta=True, quality=75, scale=1.0, size=[1920, 1350], upload_to='works/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='jpeg', keep_meta=True, quality=75, scale=1.0, size=[1920, 1350], upload_to='works/%Y/%m/%d/'),
        ),
    ]
