# Generated by Django 4.0.4 on 2022-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='works/%Y/%m/%d/%H/%M%S'),
        ),
    ]
