# Generated by Django 4.0.4 on 2022-09-06 17:10

from django.db import migrations
import django_resized.forms
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='images/1234.jpg', force_format='jpeg', keep_meta=True, null=True, quality=75, scale=0.5, size=[800, 800], upload_to=user.models.User.image_upload_to),
        ),
    ]
