# Generated by Django 4.0.4 on 2022-09-06 19:54

import django.core.validators
from django.db import migrations, models
import django_resized.forms
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='images/1234.jpg', force_format='jpeg', keep_meta=True, null=True, quality=75, scale=1.0, size=[500, 500], upload_to=user.models.User.image_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_]+\\Z')]),
        ),
    ]
