# Generated by Django 4.0.4 on 2022-08-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='social',
            new_name='instagram',
        ),
    ]
